project:
  type: website


website:
  title: "Musings"
  html-math-method: "katex"
  twitter-card: true
  navbar:
    right:
      - icon: eye
      - icon: linkedin
        href: https://www.neeldhara.com
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: theme.scss
    css: styles.css
    include-after-body: footer.html



